<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Site.Master" AutoEventWireup="true" CodeBehind="EditTowns.aspx.cs" Inherits="ContactsList.Admin.EditTowns" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../Content/admin.edit.towns.css" rel="stylesheet" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
      
    <div class="container">
        <h3>Редактирование городов:</h3>
         
        <div id="addTown">
        <asp:FormView ID="AddTownFormView"             
            InsertMethod="AddTown"
            ClientIDMode="Static"
            DefaultMode="Insert"
            RenderOuterTable="false"
            ItemType="ContactsList.Admin.Models.AddTownViewModel"
            runat="server">
            <InsertItemTemplate>
                <asp:TextBox ID="txtCountry" Text="<%# BindItem.Name %>" runat="server" />
                <asp:Button ID="Button1" CssClass="btn btn-default"  runat="server" CommandName="Insert" Text="Добавить город" />
            </InsertItemTemplate>
        </asp:FormView>
        </div>

        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>

        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <asp:DropDownList ID="ddlCountry"
                    AutoPostBack="true"
                    ClientIDMode="Static"
                    SelectMethod="GetCountries"
                    DataTextField="Name"
                    DataValueField="ID"
                    ItemType="ContactsList.Admin.Models.CountryViewModel"
                    runat="server">
                </asp:DropDownList>
                <asp:GridView ID="TownsGridView"
                     ClientIDMode="Static"
                    runat="server"
                    ItemType="ContactsList.Admin.Models.TownViewModel"
                    CssClass="table table-bordered table-striped table-selectable"
                    DataKeyNames="ID"
                    AutoGenerateColumns="false"
                    AutoGenerateDeleteButton="true"
                    AutoGenerateEditButton="true"
                    SelectMethod="GetTowns"
                    DeleteMethod="RemoveTown"
                    UpdateMethod="UpdateTownName"
                    OnRowDataBound="TownsGridView_RowDataBound">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Города" />
                    </Columns>
                </asp:GridView>
            </ContentTemplate>
        </asp:UpdatePanel>
        <asp:UpdateProgress ID="updateProgress" runat="server">
            <ProgressTemplate>
                <asp:Image ID="imgUpdateProgress" runat="server" ImageUrl="~/Content/ajax-loader-gears.gif" AlternateText="Загрузка ..." ToolTip="Загрузка ..." />
            </ProgressTemplate>
        </asp:UpdateProgress>
    </div>
</asp:Content>
